/* @flow */
import * as util from "./util"
export type Recipe = {
  type: "refined" | "crafted",
  materials: Array<string>,
  quantities: Array<number>,
  product: string,
  output: number
}

export const array: Array<Recipe> = [
  {type: "refined", product: "Au", materials: ["Pg", "Mo"], quantities: [1, 1], output: 1},
  {type: "refined", product: "Au", materials: ["Pg", "Cr"], quantities: [1, 1], output: 2},
  {type: "refined", product: "C+", materials: ["C"], quantities: [2], output: 1},
  {type: "refined", product: "C+", materials: ["O2", "C"], quantities: [2, 2], output: 5},
  {type: "refined", product: "C+", materials: ["O2", "C+"], quantities: [2, 1], output: 6},
  {type: "refined", product: "CO2", materials: ["Fe", "NH3"], quantities: [1, 2], output: 1},
  {type: "refined", product: "CO2", materials: ["Fr", "Fe"], quantities: [1, 1], output: 1},
  {type: "refined", product: "CO2", materials: ["Fr", "NaCl"], quantities: [2, 1], output: 1},
  {type: "refined", product: "CO2", materials: ["C+", "Na+"], quantities: [1, 2], output: 6},
  {type: "refined", product: "Ch", materials: ["Cd"], quantities: [1], output: 2},
  {type: "refined", product: "Ch", materials: ["Cd+"], quantities: [1], output: 3},
  {type: "refined", product: "Cd", materials: ["Cd", "Ch"], quantities: [1, 1], output: 4},
  {type: "refined", product: "Ch", materials: ["Cd", "Fe"], quantities: [1, 1], output: 2},
  {type: "refined", product: "Ch", materials: ["Cd", "Fe+"], quantities: [1, 1], output: 4},
  {type: "refined", product: "Ch", materials: ["Cu"], quantities: [2], output: 1},
  {type: "refined", product: "Ch", materials: ["Cu", "Fe"], quantities: [1, 1], output: 1},
  {type: "refined", product: "Ch", materials: ["Cu", "Fe+"], quantities: [1, 1], output: 3},
  {type: "refined", product: "Ch", materials: ["Cu+"], quantities: [1], output: 1},
  {type: "refined", product: "Ch", materials: ["Em"], quantities: [1], output: 1},
  {type: "refined", product: "Ch", materials: ["Em+"], quantities: [1], output: 2},
  {type: "refined", product: "Ch", materials: ["In"], quantities: [1], output: 3},
  {type: "refined", product: "Ch", materials: ["In+"], quantities: [1], output: 6},
  {type: "refined", product: "Cl", materials: ["NaCl"], quantities: [2], output: 1},
  {type: "refined", product: "Cl", materials: ["O2", "NaCl"], quantities: [2, 2], output: 5},
  {type: "refined", product: "Cl", materials: ["O2", "Cl"], quantities: [2, 1], output: 6},
  {type: "refined", product: "C", materials: ["O2"], quantities: [1], output: 1},
  {type: "refined", product: "C+", materials: ["C"], quantities: [2], output: 1},
  {type: "refined", product: "C+", materials: ["Pg", "C"], quantities: [1, 2], output: 3},
  {type: "refined", product: "C+", materials: ["Pg", "C+"], quantities: [1, 1], output: 4},
  {type: "refined", product: "C+", materials: ["O2", "C"], quantities: [2, 2], output: 5},
  {type: "refined", product: "C+", materials: ["O2", "C+"], quantities: [2, 1], output: 6},
  {type: "refined", product: "C+", materials: ["O2", "Mb"], quantities: [1, 1], output: 2},
  {type: "refined", product: "C+", materials: ["C*"], quantities: [1], output: 50},
  {type: "refined", product: "C*", materials: ["C+", "*", "*"], quantities: [50, 0, 0], output: 1},
  {type: "refined", product: "Co+", materials: ["Co"], quantities: [2], output: 1},
  {type: "refined", product: "Co+", materials: ["Pg", "Co"], quantities: [1, 2], output: 3},
  {type: "refined", product: "Co+", materials: ["Pg", "Co+"], quantities: [1, 1], output: 4},
  {type: "refined", product: "Co+", materials: ["O2", "Co"], quantities: [2, 2], output: 5},
  {type: "refined", product: "Co+", materials: ["O2", "Co+"], quantities: [2, 1], output: 6},
  {type: "refined", product: "Co+", materials: ["Pg", "Mb"], quantities: [1, 1], output: 2},
  {type: "refined", product: "Co+", materials: ["Mo", "Cr"], quantities: [1, 1], output: 2},
  {type: "refined", product: "Co+", materials: ["Cr", "C"], quantities: [1, 1], output: 2},
  {type: "refined", product: "Co+", materials: ["Cr", "C+"], quantities: [1, 1], output: 3},
  {type: "refined", product: "Co*", materials: ["Co+", "*", "*"], quantities: [50, 0, 0], output: 1},
  {type: "refined", product: "Cr", materials: ["O2", "Cr"], quantities: [1, 1], output: 3},
  {type: "refined", product: "Cr", materials: ["Mo", "C"], quantities: [1, 2], output: 3},
  {type: "refined", product: "Cr", materials: ["Mo", "C+"], quantities: [1, 1], output: 4},
  {type: "refined", product: "Cu", materials: ["C", "Ch"], quantities: [1, 1], output: 4},
  {type: "refined", product: "D", materials: ["H"], quantities: [2], output: 1},
  {type: "refined", product: "D", materials: ["H", "*"], quantities: [1, 0], output: 1},
  {type: "refined", product: "Em", materials: ["Em", "Ch"], quantities: [1, 1], output: 4},
  {type: "refined", product: "Ch", materials: ["Em", "Fe"], quantities: [1, 1], output: 4},
  {type: "refined", product: "Ch", materials: ["Em", "Fe+"], quantities: [1, 1], output: 6},
  {type: "refined", product: "FeO", materials: ["O2", "Fe"], quantities: [1, 1], output: 1},
  {type: "refined", product: "FeO", materials: ["O2", "Fe+"], quantities: [1, 1], output: 2},
  {type: "refined", product: "FeO", materials: ["O2", "Fe++"], quantities: [1, 1], output: 4},
  {type: "refined", product: "Fe", materials: ["FeO"], quantities: [5], output: 1},
  {type: "refined", product: "Fe+", materials: ["Fe"], quantities: [2], output: 1},
  {type: "refined", product: "Fe+", materials: ["Pg", "Fe"], quantities: [1, 2], output: 3},
  {type: "refined", product: "Fe++", materials: ["Fe+"], quantities: [2], output: 1},
  {type: "refined", product: "Fe++", materials: ["O2", "Pt"], quantities: [1, 1], output: 10},
  {type: "refined", product: "Fe++", materials: ["Pg", "Fe+"], quantities: [1, 2], output: 3},
  {type: "refined", product: "Fe++", materials: ["Pg", "Fe++"], quantities: [1, 3], output: 4},
  {type: "refined", product: "Fe*", materials: ["Fe++", "*", "*"], quantities: [25, 0, 0], output: 1},
  {type: "refined", product: "In", materials: ["In", "Ch"], quantities: [1, 1], output: 4},
  {type: "refined", product: "Ch", materials: ["In", "Fe"], quantities: [1, 1], output: 3},
  {type: "refined", product: "Ch", materials: ["In", "Fe+"], quantities: [1, 1], output: 5},
  {type: "refined", product: "Mb", materials: ["Mo", "Na"], quantities: [1, 2], output: 3},
  {type: "refined", product: "Mb", materials: ["Mo", "Na+"], quantities: [1, 1], output: 4},
  {type: "refined", product: "N", materials: ["O2", "Rn"], quantities: [1, 1], output: 1},
  {type: "refined", product: "NH3", materials: ["Fe", "Pf"], quantities: [1, 2], output: 1},
  {type: "refined", product: "NH3", materials: ["Fm", "Fe"], quantities: [1, 1], output: 1},
  {type: "refined", product: "NH3", materials: ["Fm", "NaCl"], quantities: [2, 1], output: 1},
  {type: "refined", product: "Na+", materials: ["Na"], quantities: [2], output: 1},
  {type: "refined", product: "O2*", materials: ["O2", "*", "*"], quantities: [50, 0, 0], output: 1},
  {type: "refined", product: "P", materials: ["Fe", "CO2"], quantities: [1, 2], output: 1},
  {type: "refined", product: "P", materials: ["Na", "Fe"], quantities: [1, 1], output: 2},
  {type: "refined", product: "P", materials: ["Na", "NaCl"], quantities: [2, 1], output: 1},
  {type: "refined", product: "Pf", materials: ["Fe", "Py"], quantities: [1, 2], output: 1},
  {type: "refined", product: "Pf", materials: ["Sb", "Fe"], quantities: [1, 1], output: 2},
  {type: "refined", product: "Pf", materials: ["Sb", "NaCl"], quantities: [2, 1], output: 1},
  {type: "refined", product: "Pf", materials: ["O2", "Ag"], quantities: [1, 1], output: 2},
  {type: "refined", product: "Py", materials: ["Cc", "Fe"], quantities: [1, 1], output: 1},
  {type: "refined", product: "Py", materials: ["Cc", "NaCl"], quantities: [2, 1], output: 1},
  {type: "refined", product: "Py", materials: ["Fe+", "U"], quantities: [1, 2], output: 1},
  {type: "refined", product: "Py", materials: ["O2", "Au"], quantities: [1, 1], output: 2},
  {type: "refined", product: "Rn", materials: ["O2", "Su"], quantities: [1, 1], output: 1},
  {type: "refined", product: "Na+", materials: ["O2", "Na"], quantities: [2, 2], output: 5},
  {type: "refined", product: "Na+", materials: ["O2", "Na+"], quantities: [2, 1], output: 6},
  {type: "refined", product: "Na+", materials: ["PG", "Na"], quantities: [1, 2], output: 3},
  {type: "refined", product: "Na+", materials: ["PG", "Na+"], quantities: [1, 1], output: 4},
  {type: "refined", product: "Na+", materials: ["Cr", "Na"], quantities: [1, 1], output: 2},
  {type: "refined", product: "Na+", materials: ["Cr", "Na+"], quantities: [1, 1], output: 2},
  {type: "refined", product: "Na+", materials: ["C+", "Na"], quantities: [1, 2], output: 6},
  {type: "refined", product: "Na+", materials: ["H3", "*"], quantities: [1, 0], output: 2},
  {type: "refined", product: "Su", materials: ["O2", "N"], quantities: [1, 1], output: 1},
  {type: "refined", product: "U", materials: ["Fe", "P"], quantities: [1, 2], output: 1},
  {type: "refined", product: "U", materials: ["Gr", "Fe"], quantities: [1, 1], output: 2},
  {type: "refined", product: "U", materials: ["Gr", "NaCl"], quantities: [2, 1], output: 1},
  {type: "refined", product: "UPl", materials: ["O2", "Co", "C"], quantities: [10, 10, 10], output: 1},
  {type: "refined", product: "UPl", materials: ["O2", "Fe", "C"], quantities: [10, 10, 20], output: 1},

  // aronium {type: "crafted", product: "Aro", materials: ["Ir", "C"], quantities: [125, 125], output: 1},
  // grantine {type: "crafted", product: "Gra", materials: ["Em", "Hr"], quantities: [125, 125], output: 1},
  // herox {type: "crafted", product: "Her", materials: ["Zn", "Pt"], quantities: [20, 20], output: 1},
  // {type: "crafted", product: "Le",  materials: ["Pu", "Ti"], quantities: [125, 125], output: 1},
  {type: "crafted", product: "AMa",  materials: ["Ch", "C+"], quantities: [25, 20], output: 1},
  {type: "crafted", product: "AP1", materials: ["Cu", "MPr"], quantities: [200, 1], output: 1},
  {type: "crafted", product: "AP2", materials: ["Cd", "MPr"], quantities: [200, 1], output: 1},
  {type: "crafted", product: "AP3", materials: ["Em", "MPr"], quantities: [200, 1], output: 1},
  {type: "crafted", product: "ASa", materials: ["N", "C"], quantities: [250, 25], output: 1},
  {type: "crafted", product: "Aci", materials: ["Fm"], quantities: [600], output: 1},
  {type: "crafted", product: "CBo", materials: ["PFi"], quantities: [1], output: 1},
  {type: "crafted", product: "CCh", materials: ["LGl", "CPu"], quantities: [1, 1], output: 1},
  {type: "crafted", product: "CPu", materials: ["HIc", "TCo"], quantities: [1, 1], output: 1},
  {type: "crafted", product: "CaS",  materials: ["Fe"], quantities: [50], output: 1},
  {type: "crafted", product: "DB", materials: ["Cu", "Fe"], quantities: [125, 125], output: 1},
  {type: "crafted", product: "DRe", materials: ["AMa", "MFa", "Ch"], quantities: [2, 4, 100], output: 1},
  {type: "crafted", product: "ECa", materials: ["Rn", "C"], quantities: [250, 25], output: 1},
  {type: "crafted", product: "FAc", materials: ["OCa", "ASa"], quantities: [1, 1], output: 1},
  {type: "crafted", product: "FFu", materials: ["LEx", "FAc"], quantities: [1, 1], output: 1},
  {type: "crafted", product: "FIg", materials: ["FFu", "QPr", "Ge"], quantities: [1, 1, 1], output: 1},
  {type: "crafted", product: "Ge",   materials: ["DB", "Her", "Le"], quantities: [1, 1, 1], output: 1},
  {type: "crafted", product: "Gla", materials: ["Fr"], quantities: [250], output: 1},
  {type: "crafted", product: "HCa", materials: ["Na"], quantities: [200], output: 1},
  {type: "crafted", product: "HIc", materials: ["ASa", "ECa"], quantities: [1, 1], output: 1},
  {type: "crafted", product: "Ii", materials: ["Aro", "MG", "Gra"], quantities: [1, 1, 1], output: 1},
  {type: "crafted", product: "LEx", materials: ["UGe"], quantities: [1], output: 1},
  {type: "crafted", product: "LGl", materials: ["Lub", "Gla"], quantities: [1, 1], output: 1},
  {type: "crafted", product: "Lub", materials: ["Gr"], quantities: [400], output: 1},
  {type: "crafted", product: "MFa", materials: ["Pt", "Fe"], quantities: [10, 50], output: 1},
  {type: "crafted", product: "MG", materials: ["Au", "Fe"], quantities: [125, 125], output: 1},
  {type: "crafted", product: "OCa", materials: ["TCo", "ECa"], quantities: [1, 1], output: 1},
  {type: "crafted", product: "PFi", materials: ["Sb"], quantities: [200], output: 1},
  {type: "crafted", product: "QPr", materials: ["CBo", "Sup"], quantities: [1, 1], output: 1},
  {type: "crafted", product: "SDe", materials: ["QPr", "CCh", "Ii"], quantities: [1, 1, 1], output: 1},
  {type: "crafted", product: "Sem", materials: ["TCo", "ASa"], quantities: [1, 1], output: 1},
  {type: "crafted", product: "Sup", materials: ["Sem", "ECa"], quantities: [1, 1], output: 1},
  {type: "crafted", product: "TC", materials: ["Su", "C"], quantities: [250, 25], output: 1},
  {type: "crafted", product: "UGe", materials: ["Cc"], quantities: [200], output: 1},
  {type: "crafted", product: "UPl", materials: ["O2", "MPl"], quantities: [400, 200], output: 1},
  {type: "crafted", product: "VCe", materials: ["Mb"], quantities: [50], output: 1},
  {type: "crafted", product: "WCe", materials: ["AHo", "AMa"], quantities: [1, 1], output: 1},
  {type: "crafted", product: "WR", materials: ["Ke"], quantities: [50], output: 1}
]

array.forEach(r => Object.freeze(r))
export const set = Object.freeze(new Set(array))

const unknown: Recipe = Object.freeze({type: "unknown", product: "Unk", materials: [], quantities: [], output: 0})

export const byMaterial = (material: string): Array<Recipe> => array.filter(i => i.materials.includes(material))
export const byProduct = (material: string): Array<Recipe> => array.filter(i => i.product === material)
export const find = (search: any, field: string = "product") => util.find(array, search, field) || unknown
export const filter = (search: any, field: string = "product") => util.filter(array, search, field)
export const any = (search: any, field: string = "product"): Array<Element> => util.any(array, search, field)
export const uniqueProperties = (field: string) => util.uniqueProperties(array, field)
export const types = Object.freeze(uniqueProperties("type"))
export const products = Object.freeze(uniqueProperties("product"))
